# -*- coding: utf-8 -*-
"""im_text_firebase_download_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1krfS61AO3F1uyeXt2KeY3xV-UXGuXVME
"""

!pip install pyrebase

import pyrebase
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
import pickle
import pandas as pd

config = {"apiKey": "AIzaSyBKZPwx75JqIFokTJR5lN4oSojbPwIWUP0",
"authDomain": "mimapp-ab524.firebaseapp.com",
"databaseURL": "https://mimapp-ab524-default-rtdb.asia-southeast1.firebasedatabase.app/",  
"storageBucket": "mimapp-ab524.appspot.com"
}

firebase = pyrebase.initialize_app(config)

db = firebase.database()
values = db.child("Text").get()
df = pd.DataFrame(columns = ['message', 'label_maj'])
for row in values.each():
    df2 = {'message': row.val()['message'], 'label_maj': int(row.val()['label'])}
    df = df.append(df2, ignore_index = True)
raw_data = df
def clean_text(x):
    x = x.replace("do't", "don't")
    x = x.replace("'ve", "have")
    return x
raw_data['message'] = raw_data['message'].apply(clean_text)
X_train = raw_data['message']
y_train = raw_data['label_maj']
y_train = y_train.astype('int')
count_vect = pickle.load(open("count_vect.pkl", "rb"))
clf = pickle.load(open('clf.pkl', 'rb'))
count_vect.fit(X_train)
count_vect_transform = count_vect.transform(X_train)
count_vect_transform.toarray()
tfidf_vect = TfidfTransformer()
X_train_tfidf = tfidf_vect.fit(count_vect_transform)
X_train_tfidf_transform = X_train_tfidf.transform(count_vect_transform)
clf = MultinomialNB().fit(X_train_tfidf_transform, y_train)
pickle.dump(clf, open('clf.pkl', 'wb'))

!git init

!git add 'clf.pkl'

!git commit -m "new model"

!git remote add origin https://AdityaG09:xxxxxx@github.com/AdityaG09/im-text-app.git

!git push origin master

!git remote rm origin