# -*- coding: utf-8 -*-
"""im_image_firebase_download_data.ipynb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ma7vyvl_eZp_J8g8xLJpniuD4p4sOlKp

## **CI / CD PROCEDURE FOR IMAGE CLASSIFICATION MODEL:**
"""

!pip install pyrebase

import pyrebase

config = {"apiKey": "AIzaSyBKZPwx75JqIFokTJR5lN4oSojbPwIWUP0",
"authDomain": "mimapp-ab524.firebaseapp.com",
"databaseURL": "https://mimapp-ab524-default-rtdb.asia-southeast1.firebasedatabase.app/",  
"storageBucket": "mimapp-ab524.appspot.com"
}

firebase = pyrebase.initialize_app(config)

import pandas as pd
import tensorflow as tf
from tensorflow import keras

import os

db = firebase.database()
values = db.child("Image").get()
print(values.val())

os.mkdir("/content/data/")
os.mkdir("/content/data/important/")
os.mkdir("/content/data/unimportant/")

for row in values.each():
  if int(row.val()['label']) == 0:
    #!wget -P /content/data/important/ https://st2.depositphotos.com/2134479/8869/v/950/depositphotos_88695940-stock-illustration-mathematical-vector-seamless-texture-with.jpg
    !wget -P /content/data/important/ row.val()['message']

  elif int(row.val()['label']) == 1:
    #!wget -P /content/data/unimportant/ https://www.wishesmsg.com/wp-content/uploads/good-morning-greetings.jpg
    !wget -P /content/data/unimportant/ row.val()['message']

num_skipped = 0
for folder_name in ("important", "unimportant"):
    folder_path = os.path.join("/content/data", folder_name)
    for fname in os.listdir(folder_path):
        fpath = os.path.join(folder_path, fname)
        try:
            fobj = open(fpath, "rb")
            is_jfif = tf.compat.as_bytes("JFIF") in fobj.peek(10)
        finally:
            fobj.close()

        if not is_jfif:
            num_skipped += 1
            # Delete corrupted image
            os.remove(fpath)

print("Deleted %d images" % num_skipped)

image_size = (180, 180)
batch_size = 32

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "/content/data",
    seed=1337,
    image_size=image_size,
    batch_size=batch_size,
)

model1 = keras.models.load_model('imimage.h5')

train_ds = train_ds.prefetch(buffer_size=32)

epochs = 50

#callbacks = [
#    keras.callbacks.ModelCheckpoint("save_at_{epoch}.h5"),
#]
model1.compile(
    optimizer=keras.optimizers.Adam(1e-3),
    loss="binary_crossentropy",
    metrics=["accuracy"],
)
model1.fit(
    train_ds, epochs=epochs, 
    #callbacks=callbacks,
)

img = keras.preprocessing.image.load_img("/content/data/important/depositphotos_88695940-stock-illustration-mathematical-vector-seamless-texture-with.jpg", target_size=image_size)
img_array = keras.preprocessing.image.img_to_array(img)
img_array = tf.expand_dims(img_array, 0)  # Create batch axis

predictions = model1.predict(img_array)
score = predictions[0]
print(score)

img = keras.preprocessing.image.load_img("/content/data/unimportant/good-morning-greetings.jpg", target_size=image_size)
img_array = keras.preprocessing.image.img_to_array(img)
img_array = tf.expand_dims(img_array, 0)  # Create batch axis

predictions = model1.predict(img_array)
score = predictions[0]
print(score)

# OLD DATASET TEST
!wget !wget -P /content/ https://www.morninggreetings.com/wp-content/uploads/2021/06/Wishing-All-Of-You-Good-Day.jpg
img = keras.preprocessing.image.load_img("/content/Wishing-All-Of-You-Good-Day.jpg", target_size=image_size)
img_array = keras.preprocessing.image.img_to_array(img)
img_array = tf.expand_dims(img_array, 0)  # Create batch axis

predictions = model1.predict(img_array)
score = predictions[0]

print(score)

model1.save("/content/imimage.h5", save_format='h5')

